# this is a sample schema file for a feature object.

---
initial_entries: 12
randomize: true
id: {{uuid()}}
user: {{.firstname}} {{.lastname}}
title: {{.features}} {{.modifiers}}
icon: {{.icon}}
created:  {{.itemtimestamp}}
modified:  {{.itemtimestamp}}
enabled:  {{.boolean}}
...
